apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "djehuty.fullname" . }}-config
  labels: {{- include "djehuty.labels" . | nindent 4 }}
data:
  config.json: |-
{{ include "djehuty.configJson" . | indent 4 }}
