{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "djehuty.fullname" . }}-secrets
  labels: {{- include "djehuty.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- range $name, $contents := .Values.secrets.files }}
  {{ $name }}: |-
    {{- $contents | nindent 4 }}
  {{- end }}
{{- end }}
