{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "virtuoso.fullname" . }}
  labels: {{- include "virtuoso.labels" . | nindent 4 }}
type: Opaque
stringData:
  DBA_PASSWORD: {{ .Values.dbaPassword | quote }}
{{- end }}
