apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtuoso.fullname" . }}
  labels: {{- include "virtuoso.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "virtuoso.selectorLabels" . | nindent 4 }}
  ports:
    - name: sparql
      port: {{ .Values.service.port }}
      targetPort: sparql
